# BUILD SETTINGS

[build]
command = "npm run build"
publish = "dist"

# REDIRECTS

# Netlify default subdomain

# Handled here because the Netlify subdomain is not a custom domain and cannot be managed via Netlify's domain management page.
[[redirects]]
from = "https://timoetjen.netlify.app/*"
to = "https://timoetjen.eu/:splat"
status = 301
force = true

# Custom domains

# All other redirects are managed via Netlify's domain management page and do not need to be declared here.
